### ISSUE TITLE
Add more sources

### ISSUE THREAD

**Issue by AykhanUV** [iswilljr/wovie#15]
Hey can you add more stream api's? You cam find some of them [here](https://fmhy.net/videopiracyguide#streaming-apis) moviesapi.club is the most stable as i see

**Comment by athretv** [comment]
Hey also how can i change color of site it is purple rn

**Comment by iswilljr** [comment]
> Hey can you add more stream api's? You cam find some of them [here](https://fmhy.net/videopiracyguide#streaming-apis) moviesapi.club is the most stable as i see

Yeah I'll add some more sources

> Hey also how can i change color of site it is purple rn

You can change it in the [tailwind config](https://github.com/iswilljr/wovie/blob/master/tailwind.config.mjs#L14), change the primary color for one of the tailwind colors or you can [generate one here](https://uicolors.app/create)

**Comment by athretv** [comment]
You can close this issue if you want
Thanks for help

**Comment by iswilljr** [comment]
I added the moviesapi.club source, it also seemed to me the most stable. 

If you find more sources feel free to ask for them to be added.

**Comment by athretv** [comment]
Hi can you please add more sources? I have some like vidlink.pro, vidsrc.vip

**Comment by iswilljr** [comment]
Vid Link source is so good 🔥

Thanks for sharing

**Comment by athretv** [comment]
Hey are you going to add them?

**Comment by iswilljr** [comment]
They've been already added a few days ago

**Comment by athretv** [comment]
Hey I have a suggestion here, you can remove some sources that are just copying others, like vidsrc.to, vidsrc.vip(they just use vidlink.pro and just put watermark in player) and add some that i have found.

https://embed.spencerdevs.xyz/
And
https://rivestream.live/embed/docs#demo

Rive fetches from like 30 streaming services so there is no chance you can't find what you're looking for

https://111movies.com/ 
This one is good too

**Comment by iswilljr** [comment]
@AykhanUV Hey I added the sources

sorry it took so long I kinda forgot about this, you can open a new issue next time for new source requests

**Comment by athretv** [comment]
@iswilljr can i ask what is new "rank" in 
src/utils/sources.ts?

**Comment by iswilljr** [comment]
it's to order the sources, for now it's based on how many people are using them
