### ISSUE TITLE
Feature request: Continue Watching Section

### ISSUE THREAD

**Issue by Jeromi-e** [iswilljr/wovie#20]
Hi, can you please add continue watching section to your site?

**Comment by athretv** [comment]
This would be very good feature. I think you can do it by adding backend storage or using API Endpoint.

**Comment by iswilljr** [comment]
Yeah that would be a good feature. I don't really have much time to work on this but I'll definetly try to implement it asap

**Comment by athretv** [comment]
Hey, sorry if i disturb you but are you going to update soon?

**Comment by iswilljr** [comment]
I will try to work on it this weekend

**Comment by iswilljr** [comment]
Hey could you test this and see if is working good for you guys? [betawovie.vercel.app](https://betawovie.vercel.app)
Just enter to the website, watch a show or a movie for a few seconds and then go to the homepage and try reloading, there should be the new watching section there

@AykhanUV if is not working on you tv, could you enter in this website [whatismybrowser.com](https://www.whatismybrowser.com) on your tv and share me the url under the section "Your web browser's unique URL:"

**Comment by athretv** [comment]
Hi, yes it works nice on pc and phone, but on tv it does not
Here is url you asked for:
whatismybrowser.com/w/K2K78AN

**Comment by Jeromi-e** [comment]
> Hey could you test this and see if is working good for you guys? [betawovie.vercel.app](https://betawovie.vercel.app) Just enter to the website, watch a show or a movie for a few seconds and then go to the homepage and try reloading, there should be the new watching section there
> 
> @AykhanUV if is not working on you tv, could you enter in this website [whatismybrowser.com](https://www.whatismybrowser.com) on your tv and share me the url under the section "Your web browser's unique URL:"

Hey works for me very nice. Thanks

**Comment by iswilljr** [comment]
> Here is url you asked for:
> whatismybrowser.com/w/K2K78AN

Thanks, I'll see if I can find a way to make the js code work for most browsers, otherwise I'll make it work without js

**Comment by iswilljr** [comment]
@AykhanUV can you check again on your smart tv? [betawovie.vercel.app](https://betawovie.vercel.app/)

I made the js code target old browser versions

**Comment by athretv** [comment]
> @AykhanUV can you check again on your smart tv? [betawovie.vercel.app](https://betawovie.vercel.app/)
> 
> I made the js code target old browser versions

I tried it now and it works pretty well

**Comment by iswilljr** [comment]
Added continue watching section in #21

**Comment by AykhanUV** [comment]
Hey new feature stopped working for me, it does not work at all

**Comment by athretv** [comment]
Hey i have a issue here, i tried to self host this and im getting a error when doing pnpm build i tried vercel too that did not work too
Here is log:

> wovie@0.1.0 build C:\Users\Ayxan\Desktop\wovie-master
> astro check && astro build

22:23:50 [types] Generated 175ms
22:23:50 [check] Getting diagnostics for Astro files in C:\Users\Ayxan\Desktop\wovie-master...
Result (54 files):
- 0 errors
- 0 warnings
- 0 hints

22:24:17 [types] Generated 150ms
[Astro DB Error] Attempting to build without the --remote flag or the ASTRO_DATABASE_FILE environment variable defined. You probably want to pass --remote to astro build.
  Hint:
    Learn more connecting to Studio: https://docs.astro.build/en/guides/astro-db/#connect-to-astro-studio
  Location:
    C:\Users\Ayxan\Desktop\wovie-master\node_modules\.pnpm\@astrojs+db@0.14.3_@types+react@18.3.12_kysely@0.27.4_react@18.3.1\node_modules\@astrojs\db\dist\core\integration\index.js:139:17
  Stack trace:
    at astro:build:start (file:///C:/Users/Ayxan/Desktop/wovie-master/node_modules/.pnpm/@astrojs+db@0.14.3_@types+react@18.3.12_kysely@0.27.4_react@18.3.1/node_modules/@astrojs/db/dist/core/integration/index.js:139:17)
    at AstroBuilder.build (file:///C:/Users/Ayxan/Desktop/wovie-master/node_modules/.pnpm/astro@4.16.10_@types+node@16.18.11_rollup@4.22.4_terser@5.36.0_typescript@5.6.3/node_modules/astro/dist/core/build/index.js:113:11)
    at async build (file:///C:/Users/Ayxan/Desktop/wovie-master/node_modules/.pnpm/astro@4.16.10_@types+node@16.18.11_rollup@4.22.4_terser@5.36.0_typescript@5.6.3/node_modules/astro/dist/core/build/index.js:51:3)
    at async runCommand (file:///C:/Users/Ayxan/Desktop/wovie-master/node_modules/.pnpm/astro@4.16.10_@types+node@16.18.11_rollup@4.22.4_terser@5.36.0_typescript@5.6.3/node_modules/astro/dist/cli/index.js:147:7)
 ELIFECYCLE  Command failed with exit code 1.

C:\Users\Ayxan\Desktop\wovie-master>

**Comment by iswilljr** [comment]
Yeah I need to update a guide for setting up the project, this new feature requires some new env varibles and some other changes

I will do it in a few hours probably

**Comment by iswilljr** [comment]
Added a guide for it https://github.com/iswilljr/wovie?tab=readme-ov-file#how-to-get-env-variables

**Comment by AykhanUV** [comment]
hey how do i get TURSO_DATABASE_URL and TURSO_AUTH_TOKEN?
You did not explain in there

**Comment by athretv** [comment]
Hey what should i put in TURSO_AUTH_TOKEN?
There is issue when i try to create account it says something went wrong

**Comment by iswilljr** [comment]
did you pull the lastest changes? That shouldn't be a problem anymore
if you did and the error persists try setting `TURSO_DATABASE_URL` the same value as `ASTRO_DB_REMOTE_URL`
and `TURSO_AUTH_TOKEN` the same value as `ASTRO_DB_APP_TOKEN`

**Comment by athretv** [comment]
I pulled and set .env as you said still getting this error. Can you try it i put the site url in about of repo

**Comment by iswilljr** [comment]
Yeah my bad, forgot one step. It should be good now, pull the latest changes and it should be ok, also make sure the `BETTER_AUTH_URL` and `BETTER_AUTH_TRUSTED_ORIGINS` are set to the correct url (it should be the one you are going to visit on you pc, tv, etc...)

**Comment by athretv** [comment]
Still the same thing btw does not work
Also update when i try same email to sign up it says: 
User with this email already exists
But when i try to log in or create another account still gives the same error

**Comment by iswilljr** [comment]
Hmm, that's odd. I tried it locally with your env variables and it was working good for me, can you try doing all the steps again and making sure the env variables are set on vercel, then try redeploying on vercel

**Comment by athretv** [comment]
Hi, i don't know if this is issue with turso but i can't remove any account records from there.
It gives this error:
SQLITE_CONSTRAINT: SQLite error: FOREIGN KEY constraint failed

**Comment by iswilljr** [comment]
you need to remove any other record on the other tables that references the account you are trying to delete

why are you trying to remove them?

**Comment by athretv** [comment]
It was just a demo account, just want to keep things simple

**Comment by AykhanUV** [comment]
Still can't remove i removed all with the same id

**Comment by Jeromi-e** [comment]
@iswilljr mate can u add a box to clear your watching section? Or select then delete specific ones
