### ISSUE TITLE
Self-Host Issues

### ISSUE THREAD

**Issue by iswilljr** [iswilljr/wovie#24]
Needed Env Variables:
- The Movie Database API Key: `TMDB_KEY`
- Auth: `BETTER_AUTH_URL`, `BETTER_AUTH_TRUSTED_ORIGINS`, `BETTER_AUTH_SECRET`
- Turso: `TURSO_DATABASE_URL`, `ASTRO_DB_REMOTE_URL`, `TURSO_AUTH_TOKEN`, `ASTRO_DB_APP_TOKEN`

**Comment by iswilljr** [comment]
@AykhanUV let's move the discussion here

can you try to do all the steps again and make sure your environment variables are set in vercel, then try to deploy again in vercel

**Comment by athretv** [comment]
@iswilljr I have tried it now it works, problem was i did not set environment variables in vercel, now issue is fixed
