### ISSUE TITLE
qol suggestions

### ISSUE THREAD

**Issue by aaru111** [iswilljr/wovie#25]
and next/prev episode buttons below the player 

create a discord server for interaction with people for more suggestions and improvements

take some inspirations from this website
https://mapple.tv/

**Comment by iswilljr** [comment]
I'll add the next and prev buttons

I'm not sure about the discord server but I'll think about it

**Comment by aaru111** [comment]
also add a button that lets you remove movies/shows from continue watching

and what does the telescope button do which is after the search button, it just opens search for me

discord server would be nice so do consider it

**Comment by iswilljr** [comment]
> also add a button that lets you remove movies/shows from continue watching

this was already implemented a few days ago

> and what does the telescope button do which is after the search button, it just opens search for me

yeah it opens the search page, it is just to show the results in the same way that's shown in the homepage

**Comment by aaru111** [comment]
nice I love this website

tho can you edit like the player?
if yes can you add hold to 2x, double tap to seek and default preferences.

there is also one thing I dislike about the default player which is when I pause and tap the screen the player menu just stays there it is annoying.
if it can be fixed thatd be a great W.

also when I remove the continue watching and refresh the page it comes back do fix it too sometimes it doesn't even register 😔

**Comment by iswilljr** [comment]
Unfortunately I can't edit the player, so there's no much I can do. I also hate that bug haha
but you can switch to another source (select it down the player) and they might not have a bug like that one

> also when I remove the continue watching and refresh the page it comes back do fix it too sometimes it doesn't even register

oh yeah your're right, seems that they go after a few minutes, it's probably because of the browser's cache
I'll see if I can fix it
