### ISSUE TITLE
Smart tv bug

### ISSUE THREAD

**Issue by AykhanUV** [iswilljr/wovie#8]
So when i try to search something on my smart tv on wovie the movies/series just won't appear

**Comment by iswilljr** [comment]
Could you provide a video about this?

**Comment by athretv** [comment]
Video was larger than 10 mb so i uploaded on mediafire you can see it in this [link](https://www.mediafire.com/file/dzi1nnrlpt0j0u2/lv_0_20240920174848.mp4/file)

**Comment by athretv** [comment]
There are also bugs on mobile, pc while searching. For example i wanna search 'winnie the pooh', it shows results till 'winnie the' after typing pooh nothing shows up and after i delete that and type another name like 'spider man' the search is completely bugged snd won't show results till i refresh the page

**Comment by iswilljr** [comment]
Hey I think most of the issues with the search typing are fixed now, btw I could not reproduce the smart tv bug, for me it was working normally but I've updated the way is was working before and maybe now it works good for you. 

Let me know if the issue persists

**Comment by athretv** [comment]
Yeah the search works normally now. But on my tv issue still persists. I did research and saw it may be because of tv browser not supporting new JavaScript code

**Comment by iswilljr** [comment]
Maybe I should add like a explore page with advanced search, filters, sorting, etc. I'll try to add it when I have the time

**Comment by athretv** [comment]
still nothing?

**Comment by iswilljr** [comment]
@AykhanUV I added a basic explore page, hope it helps!

<https://wovie.vercel.app/explore>

**Comment by athretv** [comment]
Yeah i see that button on pc now. But there is problem there is no search bar in mobile ui so explore page button is not showing
![Screenshot_2024-10-14-17-27-47-717_net waterfox android release](https://github.com/user-attachments/assets/8ecc7228-836d-40b6-8b6b-f150189652f6)
Same goes for tv, i also tried going to /explore/ page and movies won't still load.

**Comment by athretv** [comment]
Hey is it possible for you to replace explore page function to html instead of js? I did research and the cause may be because of modern JS code

**Comment by iswilljr** [comment]
Yeah I just made it work like that too, you should be able to search now. Type then press Enter and it should work without js

**Comment by athretv** [comment]
It works now thanks
